### ISSUE TITLE
Latest update breaks downstream crates

### ISSUE THREAD

**Issue by dfaust** [octplane/fsevent-rust#13]
It seems you released a breaking change without bumping to a new major version.
This is causing problems downstream, see: passcod/notify#153

Could you yank the latest version on crates.io and release a new major version?

**Comment by octplane** [comment]
Indeed, it is a breaking change...

**Comment by octplane** [comment]
- I have yanked both crates.

**Comment by phaazon** [comment]
Thank you <3

**Comment by dfaust** [comment]
Great, thank you.

**Comment by passcod** [comment]
Thank you all :)
