### ISSUE TITLE
notify failing on MacOS due to new fsevent-sys update

### ISSUE THREAD

**Issue by NathanSWard** [octplane/fsevent-rust#36]
On the [bevy](https://github.com/bevyengine/bevy) github page, our CI builds are failing due to a recent update within the `fsevent-sys` crate.
See CI failures [here](https://github.com/bevyengine/bevy/pull/2149/checks?check_run_id=2567791064).

CI failed due to: 
```
error[E0308]: mismatched types
   --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.7/src/fsevent.rs:361:17
    |
361 |                 callback,
    |                 ^^^^^^^^ expected `u32`, found enum `c_void`
    |
    = note: expected fn pointer `extern "C" fn(_, _, _, _, *const u32, *const u64)`
                  found fn item `extern "C" fn(_, _, _, _, *const c_void, *const c_void) {callback}`
```

Here is the related `notify` [issue](https://github.com/notify-rs/notify/issues/314)

**Comment by Skareeg** [comment]
It would be best to increase the crate's Major version level after an API change like this. The notify crate references this crate by Major version level ("3"). Bevy depends on notify, and thus this error above happens.

**Comment by erickt** [comment]
I have a fix for this in #38

**Comment by NathanSWard** [comment]
Closing this in favor of https://github.com/octplane/fsevent-rust/pull/38

**Comment by NathanSWard** [comment]
Meant to close the PR not this issue... 😅
